### ISSUE TITLE
Xiaomi Bluetooth Temperature & Humidity Monitor

### ISSUE THREAD

**Issue by MynahPL** [Hypfer/Cybele#4]
Is there a chance for adding the Mi Temperature & Humidity Sensor? It seems like it should be fairly similar to the Mi Flora configuration but I am lacking the skill to change it so it would work with this device. I have 2 of these so if you need any data I hope I would be able to extract / provide it if needed.
![mi-bluetooth-temperature-humidity-monitor](https://user-images.githubusercontent.com/30555913/73119216-e1715c80-3f5e-11ea-8423-78c39b9dca93.jpg)

Amazing work, thanks!

**Comment by Hypfer** [comment]
I'm sorry but please don't post feature requests like these in this repo. I just can't and won't support any devices/frameworks/large features I don't own or use because they will sooner or later become an unmaintainable mess which keeps me from working on the project.

I don't want this to become a second Valetudo :/

It should be fairly easy to do, though. Temperature, Humidity and Battery level are all part of the advertising data so you don't even have to connect to it.
See https://github.com/hannseman/homebridge-mi-hygrothermograph#technical-details
The service UUID is most likely "0000fe95-0000-1000-8000-00805f9b34fb"


As examples you can look at the Oral-B toothbrush device as well as the MiScale device which currently both pull their information from the advertising data.


There are also a lot more of those Xiaomi bluetooth temperature sensors so it might make sense to support all of them (if possible)

**Comment by marekbarczyk** [comment]
https://github.com/marekbarczyk/Cybele/blob/master/lib/devices/MiHygrothermographDevice.js
